version: '3.8'

services:
  app:
    build: ./src
    container_name: app
    volumes:
      - ./src:/src
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
